name: scanpy_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.11.3
  - array-api-compat=1.11.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - colorama=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - exceptiongroup=1.2.2
  - fonttools=4.56.0
  - freetype=2.12.1
  - h5py=3.13.0
  - hdf5=1.14.3
  - joblib=1.4.2
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - legacy-api-wrap=1.4.1
  - lerc=4.0.0
  - libaec=1.1.3
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.12.1
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - liblzma=5.6.4
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxml2=2.13.6
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - llvmlite=0.44.0
  - matplotlib-base=3.10.1
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.5
  - networkx=3.4.2
  - numba=0.61.0
  - numpy=2.1.3
  - openjpeg=2.5.3
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pillow=11.1.0
  - pip=25.0.1
  - pthread-stubs=0.4
  - pynndescent=0.5.13
  - pyparsing=3.2.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytz=2024.1
  - qhull=2020.2
  - readline=8.2
  - scanpy=1.10.4
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - session-info=1.0.0
  - setuptools=75.8.2
  - six=1.17.0
  - statsmodels=0.14.4
  - stdlib-list=0.11.1
  - tbb=2022.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tqdm=4.67.1
  - tzdata=2025a
  - umap-learn=0.5.7
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - annoy==1.17.3
      - anyio==4.8.0
      - appnope==0.1.4
      - arboreto==0.1.6
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - attrs==25.2.0
      - babel==2.17.0
      - bbknn==1.6.0
      - beautifulsoup4==4.13.3
      - biopython==1.85
      - bleach==6.2.0
      - bokeh==3.7.3
      - boltons==25.0.0
      - cellphonedb==5.0.1
      - celltypist==1.6.3
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.1
      - chex==0.1.89
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - ctxcore==0.2.0
      - cython==3.0.12
      - cytoolz==1.0.1
      - dask==2025.5.1
      - debugpy==1.8.13
      - decorator==5.2.1
      - decoupler==2.0.4
      - defusedxml==0.7.1
      - dill==0.4.0
      - distlib==0.3.9
      - distributed==2025.5.1
      - dm-tree==0.1.9
      - docrep==0.3.2
      - et-xmlfile==2.0.0
      - etils==1.12.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fbpca==1.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - flax==0.10.4
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - gast==0.6.0
      - geosketch==1.3
      - google-pasta==0.2.0
      - grpcio==1.71.0
      - gseapy==1.1.7
      - h11==0.14.0
      - h5netcdf==1.6.3
      - harmonypy==0.0.10
      - httpcore==1.0.7
      - httpx==0.28.1
      - humanize==4.12.3
      - identify==2.6.9
      - idna==3.10
      - igraph==0.11.8
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - interlap==0.2.7
      - ipykernel==6.29.5
      - ipython==8.22.2
      - ipython-pygments-lexers==1.1.1
      - isoduration==20.11.0
      - jaxlib==0.4.35
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - ktplotspy==0.3.2
      - lazy-loader==0.4
      - legendkit==0.3.5
      - leidenalg==0.10.2
      - liana==1.5.1
      - libclang==18.1.1
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - locket==1.0.0
      - loompy==3.0.8
      - lz4==4.4.4
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marsilea==0.5.3
      - matplotlib-inline==0.1.7
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - mistune==3.1.2
      - mizani==0.13.2
      - ml-collections==1.1.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - mudata==0.3.1
      - multidict==6.4.3
      - multipledispatch==1.0.0
      - multiprocessing-on-dill==3.5.0a4
      - namex==0.1.0
      - narwhals==1.44.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - nodeenv==1.9.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numexpr==2.11.0
      - numpy-groupies==0.11.2
      - numpyro==0.18.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.16.0
      - orbax-checkpoint==0.11.5
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - plotly==6.2.0
      - plotnine==0.14.5
      - pluggy==1.5.0
      - pre-commit==4.2.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==4.25.8
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pycirclize==1.9.0
      - pycparser==2.22
      - pygments==2.19.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - pyscenic==0.12.1
      - pyscipopt==5.4.1
      - pytest==8.3.5
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.1.post0
      - pyyaml==6.0.2
      - pyzmq==26.3.0
      - referencing==0.36.2
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.23.1
      - rpy2==3.5.17
      - scikit-image==0.25.2
      - send2trash==1.8.3
      - session-info2==0.1.2
      - simplejson==3.20.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sparse==0.16.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tblib==3.1.0
      - tensorboard==2.16.2
      - tensorboard-data-server==0.7.2
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorstore==0.1.74
      - termcolor==3.1.0
      - terminado==0.18.1
      - texttable==1.7.0
      - tifffile==2025.2.18
      - tinycss2==1.4.0
      - toolz==1.0.0
      - torch==2.2.2
      - torchmetrics==1.7.1
      - tornado==6.4.2
      - traitlets==5.14.3
      - treescope==0.1.9
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzlocal==5.3.1
      - upsetplot==0.9.0
      - uri-template==1.3.0
      - urllib3==2.3.0
      - virtualenv==20.30.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xarray==2025.4.0
      - xarray-einstats==0.9.1
      - xlsxwriter==3.2.2
      - xyzservices==2025.4.0
      - yarl==1.20.0
      - zict==3.0.0
      - zipp==3.21.0
